export const SHIPPER_REGISTER_REQUEST = "SHIPPER_REGISTER_REQUEST";
export const SHIPPER_REGISTER_VERIFY = "SHIPPER_REGISTER_VERIFY";
export const SHIPPER_REGISTER_SUCCESS = "SHIPPER_REGISTER_SUCCESS";
export const SHIPPER_REGISTER_FAIL = "SHIPPER_REGISTER_FAIL";

export const SHIPPER_GET_ORDERS_REQUEST = "SHIPPER_GET_ORDERS_REQUEST";
export const SHIPPER_GET_ORDERS_SUCCESS = "SHIPPER_GET_ORDERS_SUCCESS";
export const SHIPPER_GET_ORDERS_FAIL = "SHIPPER_GET_ORDERS_FAIL";

export const SHIPPER_CONFIRM_ORDER_REQUEST = "SHIPPER_CONFIRM_ORDER_REQUEST";
export const SHIPPER_CONFIRM_ORDER_SUCCESS = "SHIPPER_CONFIRM_ORDER_SUCCESS";
export const SHIPPER_CONFIRM_ORDER_FAIL = "SHIPPER_CONFIRM_ORDER_FAIL";
export const SHIPPER_CONFIRM_ORDER_RESET = "SHIPPER_CONFIRM_ORDER_RESET";

export const SHIPPER_PICK_ORDER_REQUEST = "SHIPPER_PICK_ORDER_REQUEST";
export const SHIPPER_PICK_ORDER_SUCCESS = "SHIPPER_PICK_ORDER_SUCCESS";
export const SHIPPER_PICK_ORDER_FAIL = "SHIPPER_PICK_ORDER_FAIL";
export const SHIPPER_PICK_ORDER_RESET = "SHIPPER_PICK_ORDER_RESET";

export const SHIPPER_SHIPPING_ORDER_REQUEST = "SHIPPER_SHIPPING_ORDER_REQUEST";
export const SHIPPER_SHIPPING_ORDER_SUCCESS = "SHIPPER_SHIPPING_ORDER_SUCCESS";
export const SHIPPER_SHIPPING_ORDER_FAIL = "SHIPPER_SHIPPING_ORDER_FAIL";
export const SHIPPER_SHIPPING_ORDER_RESET = "SHIPPER_SHIPPING_ORDER_RESET";

export const SHIPPER_DELIVERED_ORDER_REQUEST = "SHIPPER_DELIVERED_ORDER_REQUEST";
export const SHIPPER_DELIVERED_ORDER_SUCCESS = "SHIPPER_DELIVERED_ORDER_SUCCESS";
export const SHIPPER_DELIVERED_ORDER_FAIL = "SHIPPER_DELIVERED_ORDER_FAIL";
export const SHIPPER_DELIVERED_ORDER_RESET = "SHIPPER_DELIVERED_ORDER_RESET";

export const ORDER_LIST_SHIPPER_REQUEST = "ORDER_LIST_SHIPPER_REQUEST";
export const ORDER_LIST_SHIPPER_SUCCESS = "ORDER_LIST_SHIPPER_SUCCESS";
export const ORDER_LIST_SHIPPER_FAIL = "ORDER_LIST_SHIPPER_FAIL";
export const ORDER_LIST_SHIPPER_RESET = "ORDER_LIST_SHIPPER_RESET";